<?php

echo '
	<form action="http://cpd/cpd.web/global/postback.aspx" method="POST" id="aspnetForm">
			<input type="hidden" name="__LASTFOCUS" id="__LASTFOCUS" value="" />
<input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="" />
<input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUIODIwNjM0MDEPFggeFUVudmlyb25tZW50S2V5SXNLbm93bmceDkVudmlyb25tZW50S2V5BQdMT0tFUkVOHhRVc2VyTG9naW5OYW1lSXNLbm93bmgeC1VzZXJJc0tub3duaBYCZg8PFggeFlJlbWVtYmVyU2Nyb2xsUG9zaXRpb25nHgdEb2NUeXBlCylpSUhDLkNQRC5XZWIuR2xvYmFscy5IVE1MRG9jVHlwZSwgSUhDLkNQRC5XZWIsIFZlcnNpb249MjAwOS42LjEuNTQxNCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsAB4LU2Nyb2xsV2lkdGhmHgxTY3JvbGxIZWlnaHRmZBYCAgEPZBYIAgMPDxYCHgdWaXNpYmxlaGQWAmYPD2QWAh4Fc3R5bGUFTmJhY2tncm91bmQtaW1hZ2U6dXJsKC9DUEQuV0VCL2dsb2JhbC9zdHlsZS9kZWZhdWx0L2ltYWdlcy9uYXZfaGVhZGVyX2NwZC5qcGcpO2QCBQ8PFgIfCGhkZAIHD2QWAgIBDw9kFgIfCQVLYmFja2dyb3VuZC1pbWFnZTp1cmwoL0NQRC5XRUIvZ2xvYmFsL3N0eWxlL2RlZmF1bHQvaW1hZ2VzL2xvZ2luaGVhZGVyLmpwZyk7ZAIVD2QWGAIBDw8WAh8IaGQWBAIBDw8WAh4EVGV4dAUJRGF0YWJhc2U6ZGQCAw8QZBAVAQdMT0tFUkVOFQEHTE9LRVJFThQrAwFnFgFmZAIDDw8WAh8IZ2QWBAIBDw8WAh8KBQ9HZWJydWlrZXJzbmFhbTpkZAIFDw8WAh8IaGRkAgUPDxYCHwhnZBYCAgEPDxYCHwoFCVBhc3dvb3JkOmRkAgcPDxYCHwhnZBYCAgEPDxYCHwoFGUlubG9nZ2VuIG9uZGVyIHN1cGVydmlzaWVkZAIJDw8WAh8IZ2QWBAIDDw8WAh8KBQhJbmxvZ2dlbmRkAgUPDxYCHwoFCUFubnVsZXJlbmRkAgsPDxYCHwhoZBYCAgMPDxYCHwoFEEFuZGVyZSBnZWJydWlrZXJkZAINDw8WAh8IaGQWBAIBDw8WAh8KBQtTdXBlcnZpc29yOmRkAgMPEGRkFgBkAg8PDxYCHwhoZBYEAgEPDxYCHwoFC1RvZXBhc3Npbmc6ZGQCAw8QZGQWAGQCEQ8PFgIfCGhkFgQCAQ8PFgIfCgUHQ2FtcHVzOmRkAgMPEGRkFgBkAhMPDxYCHwhoZBYEAgEPDxYCHwoFB0RpZW5zdDpkZAIDDxBkZBYAZAIVDw8WAh8IaGQWBAIBDw8WAh8KBRBWZXJwbGVlZ2VlbmhlaWQ6ZGQCAw8QZGQWAGQCFw9kFgQCAQ8PFgIfCgUJbWVlciBpbmZvFgYeB29uY2xpY2sFJnNob3coJ2N0bDAwX0NQSEJfcGFuZWxMb2dpbk1vcmVJbmZvJyk7Hgtvbm1vdXNlb3ZlcgUcdGhpcy5zdHlsZS5jdXJzb3I9J3BvaW50ZXInOx4Kb25tb3VzZW91dAUcdGhpcy5zdHlsZS5jdXJzb3I9J2RlZmF1bHQnO2QCAw9kFgoCAQ8PFgIfCgWTAVZlcnNpZTogMjAwOS42LjEuNTQxNDxicj5Db3B5cmlnaHQ6ICZjb3B5OyBJbmZvaG9zIC0gSUhDIDxicj5IZWxwZGVzazogMDUwIDIwIDc5IDAwPGJyPjxhIGhyZWY9Im1haWx0bzpoZWxwZGVza0BpbmZvaG9zLmJlIj5oZWxwZGVza0BpbmZvaG9zLmJlPC9hPmRkAgMPDxYCHghJbWFnZVVybAU1L0NQRC5XRUIvZ2xvYmFsL3N0eWxlL2RlZmF1bHQvaW1hZ2VzL2xvZ29faW5mb2hvcy5qcGdkZAIFDw8WAh8OBTEvQ1BELldFQi9nbG9iYWwvc3R5bGUvZGVmYXVsdC9pbWFnZXMvbG9nb19paGMuanBnZGQCBw8PFgIfCgVmTGVnZXdlZyAxNTcgRiA8YnI+ODAyMCBPb3N0a2FtcCA8YnI+PGEgaHJlZj0iaHR0cDovL3d3dy5pbmZvaG9zLmJlIiB0YXJnZXQ9Il9ibGFuayI+d3d3LmluZm9ob3MuYmU8L2E+ZGQCCQ8PFgIfCgVhTGVnZXdlZyAxNTcvRSAwMiA8YnI+ODAyMCBPb3N0a2FtcCA8YnI+PGEgaHJlZj0iaHR0cDovL3d3dy5paGMuYmUiIHRhcmdldD0iX2JsYW5rIj53d3cuaWhjLmJlPC9hPmRkGAEFHl9fQ29udHJvbHNSZXF1aXJlUG9zdEJhY2tLZXlfXxYBBR5jdGwwMCRDUEhCJGNoZWNrYm94U3VwZXJ2aXNpb25YkS8+BC3LIYugElID+hcNng5wUg==" />
	<input name="ctl00$inputhiddenScrollPosition" type="hidden" id="ctl00_inputhiddenScrollPosition" />
			<input name="ctl00$inputhiddenChangedControls" type="hidden" id="ctl00_inputhiddenChangedControls" />


			<input  type="text" id="ctl00_CPHB_textboxUser" class="textbox" />
			<input  type="password" id="ctl00_CPHB_textboxPassword" class="textbox" />
			<input id="ctl00_CPHB_checkboxSupervision" type="checkbox" name="ctl00$CPHB$checkboxSupervision" />
			<input type="submit" name="ctl00$CPHB$buttonLogin" value="Inloggen" id="ctl00_CPHB_buttonLogin" class="button" />

	</form>
';
?>